-- MySQL Script generated by MySQL Workbench
-- Thu Jun 27 11:14:24 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`entities_types`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`entities_types` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `type` VARCHAR(7) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`entities`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`entities` (
  `id` INT(3) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `logo` VARCHAR(150) NULL,
  `email` VARCHAR(50) NOT NULL,
  `password` VARCHAR(32) NOT NULL,
  `active` BIT NOT NULL DEFAULT 1,
  `description` VARCHAR(80) NULL,
  `website_url` TEXT NULL,
  `entities_types_id` INT NOT NULL,
  `createdAt` TIMESTAMP NOT NULL,
  `updatedAt` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_entities_entities_types1_idx` (`entities_types_id` ASC) VISIBLE,
  CONSTRAINT `fk_entities_entities_types1`
    FOREIGN KEY (`entities_types_id`)
    REFERENCES `mydb`.`entities_types` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`teams`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`teams` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `entities_id` INT(3) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_teams_entities1_idx` (`entities_id` ASC) VISIBLE,
  CONSTRAINT `fk_teams_entities1`
    FOREIGN KEY (`entities_id`)
    REFERENCES `mydb`.`entities` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`experience_levels`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`experience_levels` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `experience_level` VARCHAR(9) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`departments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`departments` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `department` VARCHAR(45) NULL,
  `active` BIT NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`positions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`positions` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `position` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`types`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`types` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `type` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`workers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`workers` (
  `id` INT(3) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NOT NULL,
  `email` VARCHAR(50) NOT NULL,
  `password` VARCHAR(32) NOT NULL,
  `active` BIT NOT NULL DEFAULT 1,
  `createdAt` TIMESTAMP NOT NULL,
  `updatedAt` TIMESTAMP NULL,
  `entities_id` INT(3) NULL,
  `teams_id` INT NULL,
  `experience_levels_id` INT NOT NULL DEFAULT 1,
  `department_id` INT NOT NULL DEFAULT 1,
  `position_id` INT NOT NULL DEFAULT 1,
  `type_id` INT NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`),
  INDEX `fk_workers_entities_idx` (`entities_id` ASC) VISIBLE,
  INDEX `fk_workers_teams1_idx` (`teams_id` ASC) VISIBLE,
  INDEX `fk_workers_experience_levels1_idx` (`experience_levels_id` ASC) VISIBLE,
  INDEX `fk_workers_department1_idx` (`department_id` ASC) VISIBLE,
  INDEX `fk_workers_position1_idx` (`position_id` ASC) VISIBLE,
  INDEX `fk_workers_type1_idx` (`type_id` ASC) VISIBLE,
  CONSTRAINT `fk_workers_entities`
    FOREIGN KEY (`entities_id`)
    REFERENCES `mydb`.`entities` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_workers_teams1`
    FOREIGN KEY (`teams_id`)
    REFERENCES `mydb`.`teams` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_workers_experience_levels1`
    FOREIGN KEY (`experience_levels_id`)
    REFERENCES `mydb`.`experience_levels` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_workers_department1`
    FOREIGN KEY (`department_id`)
    REFERENCES `mydb`.`departments` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_workers_position1`
    FOREIGN KEY (`position_id`)
    REFERENCES `mydb`.`positions` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_workers_type1`
    FOREIGN KEY (`type_id`)
    REFERENCES `mydb`.`types` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`evaluators`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`evaluators` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `workers_id` INT(3) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_evaluators_workers1_idx` (`workers_id` ASC) VISIBLE,
  CONSTRAINT `fk_evaluators_workers1`
    FOREIGN KEY (`workers_id`)
    REFERENCES `mydb`.`workers` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`roles` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `role` VARCHAR(70) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`job_types`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`job_types` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `type` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`jobs_preferences`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`jobs_preferences` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `fav_techs` VARCHAR(300) NULL,
  `disliked_techs` VARCHAR(300) NULL,
  `prefered_industries` VARCHAR(300) NULL,
  `unwanted_industries` VARCHAR(300) NULL,
  `workers_id` INT(3) NOT NULL,
  `role_id` INT NOT NULL,
  `experience_levels_id` INT NOT NULL,
  `job_type_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_jobs_prefrences_workers1_idx` (`workers_id` ASC) VISIBLE,
  INDEX `fk_jobs_prefrences_role1_idx` (`role_id` ASC) VISIBLE,
  INDEX `fk_jobs_prefrences_experience_levels1_idx` (`experience_levels_id` ASC) VISIBLE,
  INDEX `fk_jobs_prefrences_job_type1_idx` (`job_type_id` ASC) VISIBLE,
  CONSTRAINT `fk_jobs_prefrences_workers1`
    FOREIGN KEY (`workers_id`)
    REFERENCES `mydb`.`workers` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_jobs_prefrences_role1`
    FOREIGN KEY (`role_id`)
    REFERENCES `mydb`.`roles` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_jobs_prefrences_experience_levels1`
    FOREIGN KEY (`experience_levels_id`)
    REFERENCES `mydb`.`experience_levels` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_jobs_prefrences_job_type1`
    FOREIGN KEY (`job_type_id`)
    REFERENCES `mydb`.`job_types` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`vacancies`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`vacancies` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NOT NULL,
  `description` VARCHAR(45) NOT NULL,
  `remote` BIT NOT NULL,
  `active` BIT NOT NULL DEFAULT 1,
  `experience_levels_id` INT NOT NULL,
  `job_type_id` INT NOT NULL,
  `roles_id` INT NOT NULL,
  `createdAt` TIMESTAMP NOT NULL,
  `updatedAt` TIMESTAMP NULL,
  `entities_id` INT(3) NOT NULL,
  PRIMARY KEY (`id`, `entities_id`),
  INDEX `fk_vacancies_experience_levels1_idx` (`experience_levels_id` ASC) VISIBLE,
  INDEX `fk_vacancies_job_type1_idx` (`job_type_id` ASC) VISIBLE,
  INDEX `fk_vacancies_roles1_idx` (`roles_id` ASC) VISIBLE,
  INDEX `fk_vacancies_entities1_idx` (`entities_id` ASC) VISIBLE,
  CONSTRAINT `fk_vacancies_experience_levels1`
    FOREIGN KEY (`experience_levels_id`)
    REFERENCES `mydb`.`experience_levels` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_vacancies_job_type1`
    FOREIGN KEY (`job_type_id`)
    REFERENCES `mydb`.`job_types` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_vacancies_roles1`
    FOREIGN KEY (`roles_id`)
    REFERENCES `mydb`.`roles` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_vacancies_entities1`
    FOREIGN KEY (`entities_id`)
    REFERENCES `mydb`.`entities` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`cvs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`cvs` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `createdAt` TIMESTAMP NOT NULL,
  `cv` TEXT NOT NULL,
  `workers_id` INT(3) NOT NULL,
  `updatedAt` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_CV_workers1_idx` (`workers_id` ASC) VISIBLE,
  CONSTRAINT `fk_CV_workers1`
    FOREIGN KEY (`workers_id`)
    REFERENCES `mydb`.`workers` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
